TARGET_TASKS = [
    "MC_F_EGO_STA", "QC_F_EGO_DYN",
    "CI_F_EXO_STA", "CM_F_EXO_DYN",

    "DE_V_EGO_STA", "IO_V_EGO_DYN",
    "HO_V_EXO_STA", "VI_V_EXO_DYN",

    "DS_E_EGO_STA", "RV_E_EGO_DYN",
    "LS_E_EXO_STA", "BT_E_EXO_DYN",
]

THEMES_MC_F_EGO_STA= [
    # --- Category 1: Everyday Domestic ---
    "Living Room Table",
    "Kitchen Island Counter",
    "Bedroom Table",
    "Bathroom Vanity Counter",
    "Laundry Room Folding Table",
    "Dining Room Table",
    "Home Office Desk",
    "Garage Workbench",
    "Outdoor Patio Table",
    "Attic Storage Desk",

    # --- Category 2: Commercial & Public Spaces ---
    "Cafe Round Table",
    "Restaurant Booth Table",
    "Library Reading Desk",
    "Classroom Student Desk",
    "Retail Checkout Counter",
    "Hotel Reception Desk",
    "Bar Counter",
    "Hospital Room Tray Table",
    "Park Picnic Table",
    "Museum Information Desk",

    # --- Category 3: Professional & Industrial ---
    "Laboratory Workbench",
    "Art Studio Worktable",
    "Professional Kitchen Prep Station",
    "Auto Mechanic Shop Table",
    "Architect's Material Sample Table", 
    "Tailor's Cutting Table",
    "Jeweler's Workbench",
    "Botanical Greenhouse Potting Bench",
    "Factory Table",
    "Carpenter's Woodworking Bench",

    # --- Category 4: Sci-Fi & Cyberpunk ---
    "Spaceship Crew Mess Hall Table", 
    "Cyberpunk Hacker's Neon Desk",
    "Mars Colony Research Station Table",
    "Sci-Fi Cantina Bar Counter",
    "Holographic Briefing Room Table",
    "Android Repair Workshop Bench",
    "Intergalactic Diner Booth Table",
    "Steampunk Airship Captain's Desk",
    "Post-Apocalyptic Scavenger's Table",
    "Time Traveler's Workbench", 

    # --- Category 5: Fantasy & Historical ---
    "Wizard's Alchemy Desk",
    "Medieval Tavern Wooden Table",
    "Pirate Ship Captain's Map Desk",
    "Ancient Egyptian Scribe's Table",
    "Enchanted Forest Flat Tree Table",
    "Gothic Vampire Castle Dining Table",
    "Dwarven Forge Stone Workbench",
    "Victorian Detective's Cluttered Desk",
    "Fairy Tale Cottage Kitchen Table",
    "Old West Saloon Card Table",
    
    # --- Category 6: Vehicles & Transit Spaces (Stationary Context) ---
    "Passenger Train Dining Car Table",
    "Airport Lounge Coffee Table", 
    "RV Motorhome Kitchen Counter",
    "Luxury Yacht Sun Deck Table",
    "Submarine Crew Dining Table", 
    "Vintage Train Cabin Table",
    "Ferry Boat Snack Bar Counter",
    "Space Station Observation Deck Table",
    "Tour Bus Fold-out Table", 
    "Cargo Ship Captain's Desk",

    # --- Category 7: Nature & Expeditions ---
    "Beachside Table", 
    "Jungle Basecamp Folding Table",
    "Desert Archaeological Dig Sorting Table",
    "Snowy Cabin Outdoor Table", 
    "Mountain Basecamp Equipment Workbench", 
    "Lakeside Tackle Prep Station", 
    "Safari Table",
    "Cave Explorer's Rock Ledge",
    "Botanical Garden Wooden Bench",
    "Summer Camp Firepit Log Table",

    # --- Category 8: Hobbies, Arts & Crafts ---
    "Knitting and Sewing Table",
    "Photography Darkroom Counter",
    "Music Producer's Studio Desk",
    "Miniature Diorama Building Desk",
    "Scrapbooking and Origami Table",
    "Amateur Radio (Ham Radio) Desk",
    "Coin Collector's Velvet Table",
    "Makeup Artist's Vanity Station",
    "Watchmaker's Repair Desk",
    "Indoor Plant Repotting Station",

    # --- Category 9: Sports & Recreation ---
    "Gym Locker Room Bench",
    "Tennis Player's Courtside Bench", 
    "Golf Clubhouse Bar Counter",
    "Ski Lodge Apres-Ski Table", 
    "Basketball Scorer's Table",
    "Bowling Alley Score Desk",
    "Billiard Room Corner Table",
    "Yoga Studio Reception Desk",
    "Boxing Gym Equipment Desk",
    "Surfer's Beach Shack Counter",

    # --- Category 10: Events, Holidays & Celebrations ---
    "Wedding Guestbook Table",
    "Children's Birthday Party Table",
    "Halloween Table",
    "Christmas Gift Wrapping Desk",
    "New Year's Eve Cocktail Table",
    "Thanksgiving Day Table",
    "Valentine's Day Romantic Dinner Table",
    "Festival Ticket Booth Counter",
    "Flea Market Vendor's Folding Table",
    "Magician's Stage Prop Table"
]

# QC_F_EGO_DYN

# CI_F_EXO_STA

THEMES_CM_F_EXO_DYN= [
    # --- Category 1: Sci-Fi & Futuristic Control Stations ---
    "Spaceship Bridge Command Console",
    "Cyberpunk Hacker's Neon Desk",
    "Mars Rover Teleoperation Station",
    "Android Testing & Repair Workbench",
    "Holographic Traffic Control Tower Desk",
    "Intergalactic Border Customs Counter",
    "Time Machine Core Control Desk",
    "Alien Artifact Scanning Table",
    "Cybernetic Limb Modification Station",
    "Neon-lit Drone Launch Control Pad",

    # --- Category 2: Fantasy, Magic & Historical ---
    "Wizard's Enchantment Altar",
    "Alchemist's Potion Mixing Desk",
    "Steampunk Airship Helm Console",
    "Medieval Castle Gate Winch Table",
    "Dwarven Forge Control Workbench",
    "Fortune Teller's Crystal Ball Table",
    "Pirate Ship Captain's Navigation Desk",
    "Haunted Castle Dungeon Control Table",
    "Clockmaker's Testing Workbench",
    "Sorcerer's Spell Casting Table",

    # --- Category 3: Industrial & Manufacturing ---
    "Factory Quality Control Station",
    "Nuclear Power Plant Control Panel",
    "Automated Assembly Line Switchboard",
    "Water Treatment Plant Control Desk",
    "Mining Operations Control Desk",
    "Steel Mill Furnace Control Desk",
    "Textile Mill Loom Control Panel",
    "Cargo Crane Operator's Console",
    "Robot Arm Programming Station",
    "Printing Press Control Deck",

    # --- Category 4: Entertainment & Performance ---
    "DJ's Neon Mixing Console",
    "TV Game Show Contestant Podium",
    "Theatrical Stage Lighting Board",
    "Escape Room Master Control Desk",
    "Magician's Illusion Prop Table",
    "Arcade Whack-a-Mole Cabinet",
    "Theme Park Ride Operator Booth",
    "Casino Slot Machine Technician Desk",
    "Puppet Theater Control Rig",
    "Stadium Scoreboard Operator Desk",

    # --- Category 5: Service, Retail & Hospitality ---
    "Coffee Shop Espresso Bar Counter",
    "Neon-lit Cocktail Bar Counter",
    "Fast Food Drive-thru Register",
    "Hotel Concierge Desk",
    "Retro Diner Jukebox Counter",
    "Movie Theater Ticket Booth",
    "Ice Cream Parlor Topping Station",
    "Airport Check-in Desk",
    "Bank Teller's Counter",
    "Cyber-Cafe Admin Desk",

    # --- Category 6: Scientific & Medical Labs ---
    "Mad Scientist's Lab Bench",
    "Chemistry Titration Station",
    "Biological Containment Glovebox",
    "Hospital ICU Monitoring Station",
    "X-Ray Technician's Control Booth",
    "Seismograph Reading Desk",
    "Deep Sea Submersible Control Panel",
    "Meteorologist's Radar Station",
    "Forensic Evidence Testing Table",
    "Optometrist's Examination Console",

    # --- Category 7: Everyday Domestic (Appliance/Tech focus) ---
    "Smart Home Control Hub Table",
    "Modern Kitchen Appliance Counter",
    "Garage Workbench with Power Tools",
    "Audiophile's Stereo System Rack",
    "Gamer's RGB PC Desk",
    "Backyard BBQ Grill Station",
    "Laundry Room Washing Machine Top",
    "DJ's Bedroom Mixing Desk",
    "Home Security Monitor Desk",
    "Podcaster's Audio Interface Desk",

    # --- Category 8: Public Infrastructure & Utilities ---
    "Subway Train Dispatcher Desk",
    "Traffic Light Control Box Station",
    "Lighthouse Keeper's Lantern Console",
    "Drawbridge Operator's Panel",
    "Dam Floodgate Control Station",
    "Radio Broadcasting Studio Desk",
    "Space Launch Countdown Console",
    "Emergency 911 Dispatch Desk",
    "Weather Siren Activation Panel",
    "Planetarium Projector Control Console",

    # --- Category 9: Security & Military ---
    "Missile Silo Launch Console",
    "Submarine Sonar Operator Desk",
    "Military Conference Room",
    "Prison Cell Door Control Desk",
    "Border Crossing Boom-Gate Console",
    "Artillery Fire Control Table",
    "Radar Tracking Station",
    "Cyber-Defense Command Center Table",
    "Naval Ship Bridge Telegraph Station",
    "Base Security Camera Console",

    # --- Category 10: Hobbies, Arts & Specialized ---
    "Model Train Layout Control Board",
    "Ham Radio Operator's Desk",
    "Sound Engineer's Mixing Console",
    "Video Editor's Color Grading Desk",
    "Music Producer's Synthesizer Stand",
    "Slot Car Racing Track Controller",
    "Pyrotechnician's Fireworks Launch Board",
    "RC Car Repair and Test Bench",
    "Drone Racing Pilot's Station",
    "VR Arcade Setup Desk"
]

THEMES_DE_V_EGO_STA= [
    # --- Category 1: Art Galleries & Exhibitions ---
    "Contemporary Art Gallery Corner",
    "School of Visual Arts Corridor Gallery",
    "Natural History Museum Dinosaur Wing",
    "Classical Sculpture Hallway",
    "Digital Art Studio L-Corridor",
    "Pop Art Exhibit Corner",
    "Photography Gallery L-Space",
    "Historical Artifact Display Wing",
    "Curator's Private Gallery Corner",
    "Modern Architecture Model Hallway",

    # --- Category 2: Tech Expos & Conventions ---
    "Robotics Expo Booth Corner",
    "AR-VR Lab Hallway Corner",
    "Optics Technology Showcase L-Corridor",
    "Automotive Tech Display Wing Corner",
    "Consumer Electronics Trade Show Aisle",
    "Smart Home Demo L-Shaped Corridor",
    "Tech Keynote Stage Backstage Hallway",
    "Startup Convention Booth L-Space",
    "Drone Flight Test Lab L-Aisle",
    "Wearable Tech Exhibition Corner Wing",

    # --- Category 3: Desert Lodges & Visitor Centers ---
    "National Park Visitor Center Hallway",
    "Canyon Lodge Corridor Corner",
    "Desert Resort L-Shaped Corridor",
    "Geological Exhibit Wing Hallway",
    "Rustic Cabin L-Shaped Living Space",
    "Mountain View Lodge L-Corridor",
    "Bryce Canyon Souvenir Shop Corner Aisle",
    "Zion Visitor Center L-Shaped Hall",
    "Desert Botanical Garden Greenhouse L-Path",
    "Southwest Native Art Gallery Wing Corner",

    # --- Category 4: Entertainment & Neon Spaces ---
    "Las Vegas Casino Carpeted Hallway",
    "Neon-lit Arcade Corner",
    "Hollywood Movie Theater L-Shaped Lobby",
    "Boutique Hotel L-Shaped Lobby",
    "Lounge Bar L-Shaped Corridor",
    "Comedy Club Backstage L-Hallway",
    "VIP Casino Lounge Corner",
    "Retro Roller Rink Corner",
    "Bowling Alley Concession Corner Hallway",
    "Esports Arena L-Shaped Corridor",

    # --- Category 5: University & Research Facilities ---
    "University Robotics Lab L-Corridor",
    "Computer Science Server Room Aisle Corner",
    "AI Research Facility Hallway",
    "Motion Capture Lab Hallway Corner",
    "Hardware Engineering Workshop L-Aisle",
    "Data Center L-Aisle",
    "Chemistry Lab Hallway Corner",
    "3D Scanning Lab Corridor Corner",
    "University Library Stack Corner",
    "Graduate Student Office L-Hallway",

    # --- Category 6: Everyday Domestic ---
    "L-Shaped Living and Dining Hallway",
    "L-Shaped Kitchen and Breakfast Nook",
    "Master Bedroom to Walk-in Closet",
    "Basement Recreation L-Shaped Corner",
    "Large Attic L-Shaped Storage Corridor",
    "Modern Loft Apartment Corner",
    "Sunroom to Study L-Shaped Hallway",
    "Home Theater Corridor Entrance",
    "Large Garage L-Shaped Workshop Corner",
    "Mansion Grand Foyer L-Shaped Corridor",

    # --- Category 7: Commercial & Retail ---
    "Supermarket Corner Aisle",
    "Clothing Store L-Shaped Fitting Area",
    "Bookstore Fiction Section L-Aisle",
    "Hardware Store L-Aisle",
    "Furniture Showroom Corner Display Wing",
    "Shoe Store L-Shaped Display Aisle",
    "Sporting Goods Camping L-Aisle Corner",
    "Toy Store Action Figure Aisle",
    "Pharmacy Cosmetics Corner",
    "Pet Store Aquarium Corner Aisle",

    # --- Category 8: Industrial & Office ---
    "Corporate Office Cubicle Maze",
    "Warehouse Storage L-Aisle",
    "Factory Assembly Line Corner",
    "Hospital Ward Hallway",
    "Printing Press Hallway Corner",
    "Mail Sorting Facility L-Aisle",
    "Auto Repair Shop L-Shaped Bay Corner",
    "Textile Factory Loom L-Aisle",
    "Food Processing Plant Corner",
    "Industrial Brewery Vat Hallway Corner",

    # --- Category 9: Sci-Fi & Virtual Environments ---
    "Spaceship Corridor Corner",
    "Cyberpunk Enclosed Alleyway",
    "Mars Colony Habitat L-Shaped Corridor",
    "Holographic Training Facility Hallway Corner",
    "Android Production Line Turn",
    "Virtual Reality Lab L-Corridor",
    "Neon Underworld Cantina Corner Alley",
    "Steampunk Engine Room Corridor Corner",
    "Intergalactic Zoo L-Shaped Enclosure Corridor",
    "Time Travel Portal L-Shaped Corridor",

    # --- Category 10: Fantasy & Historical ---
    "Castle Stone Corridor",
    "Wizard's L-Shaped Library",
    "Medieval Dungeon Cell Block",
    "Tavern L-Shaped Dining Hallway",
    "Pirate Ship Below Decks",
    "Victorian Manor Hallway",
    "Ancient Egyptian Tomb L-Corridor",
    "Elven Forest Treehouse L-Corridor",
    "Dwarven Mine L-Tunnel",
    "Old West Saloon L-Shaped Back Hallway"
]

THEMES_IO_V_EGO_DYN = [
    # --- Category 1: Living Rooms & Lounges (two distinct surfaces) ---
    "Living Room with Coffee Table and Side Shelf",
    "Apartment Lounge with Console Table and Bookshelf",
    "Penthouse Lounge with Marble Coffee Table and Bar Cart",
    "Cozy Den with Ottoman Tray and Fireplace Mantel",
    "Sunroom with Rattan Coffee Table and Plant Stand",
    "Loft Living Area with Low Table and Window Ledge",
    "Hotel Suite Lounge with Center Table and Writing Desk",
    "Mid-Century Lounge with Teak Coffee Table and Credenza",
    "Family Room with Coffee Table and TV Console",
    "Reading Nook with Side Table and Wall Shelf",

    # --- Category 2: Bedrooms & Private Spaces ---
    "Master Bedroom with Dresser Top and Nightstand",
    "Teenager's Room with Study Desk and Bed Foot Bench",
    "Hotel Room with Writing Desk and White Marble Side Table",
    "Guest Bedroom with Vanity Table and Window Bench",
    "Nursery with Changing Table and Toy Shelf",
    "College Dorm with Study Desk and Mini Fridge Top",
    "Boutique Hotel Room with Console Table and Armchair Side Table",
    "Attic Bedroom with Trunk and Windowsill",
    "Studio Apartment with Small Desk and Bed Bench",
    "Japanese Tatami Room with Low Table and Tokonoma Alcove",

    # --- Category 3: Offices & Studies ---
    "Home Office with Desk and Filing Cabinet Top",
    "Executive Office with Main Desk and Credenza",
    "Library Study with Reading Desk and Bookshelf",
    "Architect's Studio with Drafting Table and Supply Shelf",
    "Corporate Office with Desk and Side Meeting Table",
    "Law Firm Office with Desk and Document Cabinet Counter",
    "Home Study with Writing Desk and Window Ledge",
    "University Professor's Office with Desk and Book Cart",
    "Accountant's Office with Desk and Ledger Cabinet",
    "Research Office with Desk and Material Cart",

    # --- Category 4: Kitchens & Dining ---
    "Modern Kitchen with Island Counter and Breakfast Bar",
    "Farmhouse Kitchen with Prep Table and Hutch",
    "Cafe with Service Counter and Display Shelf",
    "Restaurant Kitchen with Pass Counter and Plating Station",
    "Bakery with Prep Counter and Cooling Rack",
    "Dining Room with Dinner Table and Buffet Sideboard",
    "Tea House with Preparation Table and Tea Shelf",
    "Wine Cellar with Tasting Table and Wine Rack",
    "Pizzeria with Prep Counter and Oven Ledge",
    "Cocktail Bar with Bar Top and Back Shelf",

    # --- Category 5: Workshops & Ateliers ---
    "Carpenter's Shop with Workbench and Wooden Wall Shelf",
    "Art Studio with Worktable and Supply Cart",
    "Pottery Studio with Wheel Table and Drying Rack",
    "Electronics Lab with Workbench and Parts Shelf",
    "Jeweler's Studio with Workbench and Display Case Top",
    "Leather Craft Shop with Cutting Table and Tool Rack",
    "Bicycle Repair Shop with Workbench and Parts Counter",
    "Floral Workshop with Arranging Table and Storage Shelf",
    "Tailor's Workshop with Cutting Table and Fabric Shelf",
    "Blacksmith Forge with Anvil Table and Tool Pegboard Bench",

    # --- Category 6: Retail & Commercial ---
    "Boutique Shop with Checkout Counter and Display Table",
    "Bookshop with Sales Desk and Feature Table",
    "Jewelry Shop with Counter and Display Pedestal",
    "Antique Store with Selling Table and Curio Shelf",
    "Flower Shop with Arrangement Table and Cooler Top",
    "Pharmacy with Dispensing Counter and Product Shelf",
    "Tech Store with Demo Table and Checkout Counter",
    "Pet Store with Counter and Supply Shelf",
    "Gift Shop with Register Counter and Gift Display Table",
    "Bakery Storefront with Pastry Counter and Bread Shelf",

    # --- Category 7: Medical & Wellness ---
    "Doctor's Exam Room with Supply Counter and Writing Desk",
    "Dental Clinic with Tray Table and Side Cabinet Top",
    "Veterinary Clinic with Exam Table and Supply Shelf",
    "Optometry Room with Instrument Table and Frame Display Shelf",
    "Acupuncture Clinic with Preparation Table and Herb Shelf",
    "Massage Parlor with Oil Station and Towel Shelf",
    "Physical Therapy Room with Equipment Table and Mat Stack",
    "Beauty Salon with Styling Station and Product Shelf",
    "Nail Salon with Manicure Table and Polish Wall Shelf",
    "Pharmacy Back Room with Prep Counter and Inventory Shelf",

    # --- Category 8: Entertainment & Creative ---
    "Music Recording Studio with Mixing Desk and Instrument Shelf",
    "Photography Studio with Prop Table and Equipment Cart",
    "Theater Dressing Room with Vanity Counter and Costume Rack",
    "Film Prop Storage with Prep Table and Prop Shelf",
    "Piano Practice Room with Music Stand Table and Cabinet",
    "DJ Booth with Side Table and Vinyl Record Cabinet",
    "Comedy Green Room with Snack Table and Side Counter",
    "Game Room with Board Game Table and Trophy Shelf",
    "Magic Workshop with Prop Table and Illusion Cabinet",
    "Dance Studio Lounge with Equipment Table and Bench Ledge",

    # --- Category 9: Specialty Hobby Rooms ---
    "Model Train Room with Hobby Table and Display Shelf",
    "Stamp Collector's Room with Sorting Desk and Album Shelf",
    "Painter's Studio with Worktable and Paint Cabinet",
    "Taxidermy Workshop with Prep Table and Specimen Shelf",
    "Watchmaker's Studio with Repair Bench and Parts Drawer Top",
    "Aquarist Room with Tank Stand and Supply Shelf",
    "Calligraphy Studio with Writing Desk and Ink Shelf",
    "Book Binding Studio with Work Table and Paper Shelf",
    "Beekeeper's Prep Room with Extraction Table and Jar Shelf",
    "Herbalist Studio with Mixing Table and Herb Cabinet",

    # --- Category 10: Sci-Fi, Fantasy & Historical ---
    "Spaceship Crew Quarters with Mess Table and Storage Locker Top",
    "Wizard's Tower with Alchemy Desk and Potion Shelf",
    "Medieval Chamber with Wooden Table and Armor Rack Ledge",
    "Cyberpunk Hacker Den with Tech Desk and Server Rack Top",
    "Mars Habitat Module with Work Bench and Supply Rack",
    "Egyptian Tomb Antechamber with Offering Table and Stone Altar",
    "Steampunk Workshop with Brass Bench and Gear Shelf",
    "Pirate Captain's Cabin with Map Desk and Treasure Chest Top",
    "Victorian Study with Writing Desk and Curio Cabinet",
    "Dwarven Armory with Forge Table and Weapon Rack Bench",
]

THEMES_HO_V_EXO_STA= [
    # --- Category 1: Living Rooms & Lounges ---
    "Minimalist Living Room",
    "Cozy Apartment Lounge",
    "Sunlit Sunroom",
    "Basement Recreation Room",
    "Luxury Penthouse Living Area",
    "Hotel Suite Living Room",
    "Suburban Family Room",
    "Mid-Century Modern Lounge",
    "Rustic Cabin Living Room",
    "Loft Apartment Open Space",

    # --- Category 2: Bedrooms & Private Spaces ---
    "Master Bedroom",
    "Children's Bedroom",
    "College Dorm Room",
    "Guest Bedroom",
    "Boutique Hotel Room",
    "Studio Apartment",
    "Nursery Room",
    "Teenager's Bedroom",
    "Attic Bedroom",
    "Japanese Tatami Room",

    # --- Category 3: Offices & Studies ---
    "Executive Office",
    "Home Study Room",
    "Architect's Studio",
    "Startup Office",
    "University Professor's Office",
    "Corporate Corner Office",
    "Library Reading Nook",
    "Coworking Space Pod",
    "Law Firm Office",
    "Accountant's Office",

    # --- Category 4: Kitchens & Dining ---
    "Modern Kitchen",
    "Farmhouse Kitchen",
    "Cafe Counter Area",
    "Restaurant Kitchen Pass",
    "Bakery Back Kitchen",
    "Sushi Bar Counter",
    "Pizzeria Kitchen",
    "Wine Cellar Tasting Room",
    "Butcher Shop Counter",
    "Tea House Kitchen",

    # --- Category 5: Workshops & Garages ---
    "Home Garage Workshop",
    "Auto Mechanic Bay",
    "Carpenter's Workshop",
    "Art Studio",
    "Pottery Studio",
    "Electronics Repair Bench",
    "Jeweler's Workbench",
    "Leather Crafting Workshop",
    "Bicycle Repair Shop",
    "Garden Tool Shed",

    # --- Category 6: Retail & Commercial ---
    "Clothing Boutique",
    "Shoe Store",
    "Electronics Store",
    "Bookshop",
    "Jewelry Display Room",
    "Sporting Goods Store",
    "Furniture Showroom",
    "Supermarket Aisle",
    "Flower Shop",
    "Antique Store",

    # --- Category 7: Gyms & Sports ---
    "Home Gym",
    "Commercial Gym Weight Area",
    "Yoga Studio",
    "Physical Therapy Room",
    "Boxing Gym Corner",
    "Climbing Gym",
    "Dance Studio",
    "Locker Room",
    "Swimming Pool Equipment Room",
    "Archery Range Station",

    # --- Category 8: Medical & Labs ---
    "Doctor's Office",
    "Hospital Patient Room",
    "Chemistry Lab",
    "Dental Clinic",
    "Veterinary Exam Room",
    "Optometry Room",
    "Biology Lab",
    "Science Classroom",
    "Pharmacy Back Room",
    "Radiology Suite",

    # --- Category 9: Entertainment & Creative ---
    "Music Recording Studio",
    "Theater Backstage",
    "Photography Studio",
    "Film Prop Storage",
    "Piano Practice Room",
    "Comedy Green Room",
    "DJ Booth",
    "Game Room",
    "Arcade Corner",
    "Magic Workshop",

    # --- Category 10: Sci-Fi, Fantasy & Historical ---
    "Spaceship Bridge",
    "Wizard's Tower Study",
    "Medieval Castle Chamber",
    "Cyberpunk Hacker Den",
    "Mars Habitat Module",
    "Egyptian Tomb Antechamber",
    "Steampunk Workshop",
    "Pirate Captain's Cabin",
    "Victorian Study",
    "Dwarven Armory",
]

THEMES_VI_V_EXO_DYN= [
    # --- Category 1: Security & Stealth (Guards, Intruders, Detectives) ---
    "Bank Vault Room with Large Safety Deposit Cabinet",
    "Museum Exhibition Hall with Massive Marble Pillar",
    "Art Gallery with Freestanding Display Wall",
    "Prison Block with Concrete Pillar",
    "Casino Floor with Tall Slot Machine Bank",
    "Jewelry Store with Large Display Kiosk",
    "Mansion Ballroom with Grand Piano",
    "Corporate Server Room with Tall Server Racks",
    "Warehouse with Stack of Shipping Pallets",
    "Subway Station with Thick Support Column",

    # --- Category 2: Hide & Seek / Play (Children, Parents, Pets) ---
    "Living Room with Large Sectional Sofa",
    "Backyard Garden with Wide Oak Tree",
    "Children's Playroom with Pop-up Play Tent",
    "Public Park with Large Wooden Gazebo",
    "Kindergarten Classroom with Tall Cubby Shelves",
    "Suburban Garage with Large Tool Cabinet",
    "Indoor Playground with Large Ball Pit Wall",
    "Living Room with Tall Wooden Bookshelf",
    "Basement Recreation Room with Billiard Table",
    "Home Kitchen with Large Central Island",

    # --- Category 3: Retail & Service (Shoppers, Employees, Aisles) ---
    "Supermarket with Large Freezer Unit",
    "Clothing Store with Circular Hanging Racks",
    "Bookstore with Ceiling-High Bookshelves",
    "Hardware Store with Towering Lumber Stacks",
    "Pharmacy with Prescription Counter Block",
    "Shoe Store with Tall Display Shelf",
    "Electronics Store with Large TV Display Wall",
    "Toy Store with Giant Stuffed Bear",
    "Department Store with Large Circular Display Column",
    "Florist Shop with Large Potted Ficus Tree",

    # --- Category 4: Office & Corporate (Bosses, Workers, Partitions) ---
    "Open Plan Office with Solid Room Divider",
    "Cubicle Farm with High Fabric Walls",
    "Executive Office with Tall Filing Cabinet",
    "Breakroom with Large Refrigerator",
    "Boardroom with Massive Conference Table",
    "Copy Room with Massive Industrial Printer",
    "Office Lobby with Opaque Reception Desk",
    "Architecture Studio with Scale Model Table",
    "Mailroom with Sorting Shelf Unit",
    "Coworking Space with Large Whiteboard Partition",

    # --- Category 5: Medical & Care (Nurses, Patients, Screens) ---
    "Hospital Ward with Rolling Privacy Screens",
    "Emergency Room with Rolling Privacy Screen",
    "Doctor's Clinic with Tall Medical Cabinet",
    "Dental Office with Lead-Lined X-Ray Booth",
    "Physical Therapy Room with Gym Mat Stack",
    "Pharmacy Stockroom with High Shelves",
    "Veterinary Clinic with Solid-Walled Kennel Enclosure",
    "Optometrist Room with Testing Machine",
    "Blood Donation Center with Room Dividers",
    "Psychiatric Ward with Heavy Padded Room Divider",

    # --- Category 6: Transit & Urban Streets (Pedestrians, Vehicles, Corners) ---
    "Indoor Market Hall with Central Stone Pillar",
    "Train Station Concourse with Large Information Pillar",
    "Warehouse Loading Bay with Stacked Crate Wall",
    "Train Station Waiting Room with Large Vending Machine",
    "Airport Baggage Claim with Large Baggage Carousel Machine",
    "Parking Garage with Thick Concrete Support",
    "Ferry Deck with Funnel Stack",
    "Construction Site Office with Concrete Mixer",
    "Pedestrian Plaza with Large Public Art Sculpture",
    "Community Center Hall with Stage Platform",

    # --- Category 7: Entertainment & Stage (Performers, Crew, Props) ---
    "Theater Stage with Large Prop Crate",
    "Movie Set with Fake Wall Flats",
    "Concert Venue with Giant Speaker Towers",
    "Magic Show Stage with Illusion Cabinet",
    "Backstage Area with Large Equipment Case",
    "Circus Tent with Animal Cage",
    "Arcade Center with Photo Booth Cabin",
    "Nightclub with VIP Lounge Divider",
    "Bowling Alley with Heavy Ball Rack Stand",
    "TV Studio with Large Camera Dolly Rig",

    # --- Category 8: Outdoors & Expeditions (Campers, Animals, Terrain) ---
    "Dense Forest with Fallen Giant Sequoia",
    "Desert Canyon with Massive Sandstone Boulder",
    "Mountain Lodge with Large Stone Fireplace",
    "Ski Lodge Lobby with Large Stone Fireplace",
    "Beach Shack with Large Surfboard Rack",
    "Camping Site with Large RV Motorhome",
    "Jungle Clearing with Thick Bamboo Stand",
    "Lakeside with Wooden Boathouse",
    "Safari Plains with Giant Termite Mound",
    "Cave Entrance with Stalagmite Cluster",

    # --- Category 9: Sci-Fi & Cyberpunk (Holograms, Crates, Machinery) ---
    "Spaceship Cargo Bay with Large Crate Stack",
    "Cyberpunk Workshop with Holographic Display Tower",
    "Mars Colony with Hydroponic Grow Racks",
    "Sci-Fi Laboratory with Cryo-Stasis Pod",
    "Droid Factory with Assembly Line Machine",
    "Holographic Archive with Data Pillars",
    "Intergalactic Market with Cargo Container Stack",
    "Quantum Reactor Room with Shield Wall",
    "Space Station Bay with Cargo Containers",
    "Time Machine Chamber with Core Pedestal",

    # --- Category 10: Fantasy & Historical (Knights, Assassins, Architecture) ---
    "Medieval Castle Courtyard with Stone Well",
    "Wizard's Tower with Giant Spellbook Stand",
    "Gothic Cathedral with Large Stone Confessional Booth",
    "Ancient Temple with Colossal Statues",
    "Tavern Dining Area with Large Fireplace",
    "Pirate Ship Deck with Large Wooden Cabin",
    "Victorian Manor with Grand Marble Fireplace",
    "Elven Forest with Mossy Stone Boulder",
    "Dwarven Mine with Massive Stone Pillar",
    "Old West Saloon with Large Wooden Bar Counter"
]

THEMES_DS_E_EGO_STA= [
    # --- Category 1: Global Transit Hubs (Various Modes of Transport) ---
    "International Airport Main Concourse",
    "High-Speed Rail Grand Terminal",
    "Underground Subway Transfer Labyrinth",
    "Massive Ferry Port Waiting Hall",
    "Long-haul Bus Depot Concourse",
    "Spaceport Commercial Boarding Zone",
    "Underground Hyperloop Boarding Corridor",
    "Mountain Cable Car Base Station",
    "Urban Monorail Elevated Walkway",
    "River Taxi Mega-Terminal Promenade",

    # --- Category 2: Healthcare, Wellness & Bio-Facilities ---
    "Mega Hospital Emergency Routing Corridor",
    "Veterinary Teaching Hospital Main Hall",
    "Luxury Thermal Spa Underground Tunnel",
    "Maternity Ward Neonatal Wing Corridor",
    "Infectious Disease Quarantine Zone Walkway",
    "Underground Medical Bunker Passage",
    "Physical Rehabilitation Center Track",
    "Psychiatric Facility Secure Hallway",
    "Dental Mega-Clinic Waiting Concourse",
    "Medical Research Campus Skybridge",

    # --- Category 3: Education, Science & History ---
    "University Campus Interconnected Walkway",
    "National Library Grand Stack Corridor",
    "Particle Accelerator Circular Tunnel",
    "Oceanic Research Base Underwater Tube",
    "Natural History Museum Dinosaur Wing",
    "Arctic Observatory Enclosed Walkway",
    "Agricultural Research Greenhouse Maze",
    "Space Command Training Facility Hall",
    "Art Academy Grand Sculpture Corridor",
    "Meteorological Center Radar Tower Base",

    # --- Category 4: Massive Retail & Commercial Networks ---
    "Mega Shopping Mall Grand Atrium",
    "Wholesale Warehouse (Costco-style) Main Aisle",
    "IKEA-style Furniture Maze Walkway",
    "Luxury Outlet Village Outdoor Promenade",
    "Indoor Fish Market Auction Hall",
    "Auto Mall Showroom Network",
    "Duty-Free Plaza Transfer Walkway",
    "Underground Shopping Arcade",
    "Tech Expo Trade Show Aisle",
    "Historic Grand Bazaar Covered Street",

    # --- Category 5: Entertainment, Sports & Leisure ---
    "Grand Concert Hall Foyer Junction",
    "Indoor Theme Park Main Boulevard",
    "Mega Casino Floor Navigation Path",
    "Multiplex Cinema Grand Hallway",
    "Grand Opera House Cloakroom Corridor",
    "Indoor Ski Resort Base Lodge",
    "Aquarium Shark Tunnel Approach",
    "Zoo Primate House Enclosed Corridor",
    "Water Park Indoor Transit Hub",
    "eSports Arena VIP Access Walkway",

    # --- Category 6: Corporate & Heavy Industry ---
    "Tech Giant Campus Elevated Walkway",
    "Automobile Assembly Line Safe Path",
    "Mega Data Center Server Aisle",
    "Hydroelectric Dam Interior Inspection Tunnel",
    "Underground Mining Network Main Artery",
    "Semiconductor Cleanroom Facility Corridor",
    "Global Logistics Sorting Center Walkway",
    "Skyscraper Corporate Lobby Network",
    "Film Studio Lot Soundstage Alley",
    "Printing Press Massive Floor",

    # --- Category 7: Government, Civic & Defense ---
    "National Parliament Building Corridors",
    "Supreme Court Grand Transfer Hall",
    "Pentagon-style Military HQ Ring Corridor",
    "Central Post Office Sorting Hallway",
    "City Hall Grand Civic Concourse",
    "Embassy Compound Secure Walkway",
    "Tax Bureau Public Service Hallway",
    "Immigration Center Processing Corridor",
    "Emergency Response Underground Bunker",
    "National Archives Vault Corridor",

    # --- Category 8: Hospitality & Large Conventions ---
    "Mega Resort Grand Lobby",
    "Convention Center Main Exhibition Aisle",
    "Cruise Ship Promenade Deck",
    "Ice Hotel Carved Ice Corridors",
    "Historic Grand Hotel Transfer Hallway",
    "Eco-Resort Treetop Canopy Walkway",
    "Convention Center Glass Skybridge",
    "Capsule Hotel Network Corridor",
    "Luxury Wellness Retreat Bamboo Path",
    "Underground Casino Vault Walkway",

    # --- Category 9: Sci-Fi & Futuristic Infrastructure ---
    "Mars Colony Hydroponics Wing",
    "Orbital Ring Station Main Artery",
    "Cyberpunk Neon Skywalk",
    "Droid Manufacturing Plant Catwalk",
    "Subterranean Vault Survival City",
    "Cryogenic Research Facility Corridor",
    "Intergalactic Trade Bazaar",
    "Time Travel Hub Gateway Path",
    "Holographic Archive Information Aisle",
    "Terraforming Control Center Walkway",

    # --- Category 10: Fantasy & Historical (With Thematic Signage) ---
    "Wizard's Academy Grand Corridor", 
    "Dwarven Mine Cart Network", 
    "Elven City Canopy Bridge", 
    "Victorian World's Fair Pavilion", 
    "Medieval Castle Dungeon Network", 
    "Steampunk Brass Catwalk", 
    "Ancient Temple Labyrinth", 
    "Pirate Island Smuggler's Cave", 
    "Clockwork City Plaza", 
    "Magical Creature Zoo", 
]

THEMES_RV_E_EGO_DYN= [
    # --- Category 1: Highways & Freeways (Cars, Trucks, Motorcycles) ---
    "Desert Highway",
    "Coastal Freeway",
    "City Autobahn",
    "Neon Tollway",
    "Mountain Bypass",
    "Suspension Bridge",
    "Prairie Interstate",
    "Canyon Highway",
    "Tropical Causeway",
    "Alpine Road",

    # --- Category 2: Racetracks & Motorsports (Racecars, Karts) ---
    "Formula Track",
    "NASCAR Speedway",
    "Desert Rally",
    "Go-Kart Circuit",
    "Drag Strip",
    "Motocross Track",
    "Endurance Circuit",
    "Velodrome Track",
    "Street Circuit",
    "Salt Flats",

    # --- Category 3: Wide Waterways (Speedboats, Jet Skis, Yachts) ---
    "Ocean Regatta",
    "Wide River",
    "Coastal Strait",
    "Tropical Lagoon",
    "Commercial Bay",
    "Harbor Channel",
    "Flooded City",
    "Glacial Fjord",
    "Lake Crossing",
    "Delta Waterway",

    # --- Category 4: Aviation & Aerial (Planes, Drones, Hovercrafts) ---
    "Cloud Layer",
    "Canyon Flightpath",
    "Low Altitude",
    "Stratosphere",
    "Desert Airspace",
    "Oceanic Airway",
    "Mountain Updraft",
    "Valley Flight",
    "City Skyline",
    "Hovercraft Marsh",

    # --- Category 5: Sci-Fi & Cyberpunk (Hovercars, Pods, Mechs) ---
    "Cyberpunk Expressway",
    "Maglev Tube",
    "Mars Speedway",
    "Neon Skyway",
    "Asteroid Field",
    "Wasteland Highway",
    "Lunar Rover Track",
    "Holographic Track",
    "Orbital Ring",
    "Cyber-Grid",

    # --- Category 6: Winter & Extreme Terrain (Snowmobiles, Skis) ---
    "Frozen Lake",
    "Tundra Iceway",
    "Snowy Slopes",
    "Glacier Run",
    "Avalanche Chute",
    "Arctic Ice Road",
    "Bobsled Track",
    "Ski Resort",
    "Ice Canyon",
    "Polar Straight",

    # --- Category 7: Equestrian & Animal Riding (Horses, Chariots) ---
    "Savanna Plains",
    "Desert Dunes",
    "Medieval Racetrack",
    "Roman Hippodrome",
    "Steppe Grassland",
    "Forest Clearing",
    "Beach Shoreline",
    "Highland Plateau",
    "Oasis Trail",
    "Tundra Expanse",

    # --- Category 8: Active Mobility (Bicycles, Runners, Skaters) ---
    "Olympic Track",
    "City Marathon",
    "Boardwalk Path",
    "Park Cycleway",
    "Highway Shoulder",
    "Riverbank Trail",
    "BMX Dirt Track",
    "Roller Derby",
    "Bridge Walkway",
    "Campus Quad",

    # --- Category 9: Fantasy & Historical (Magic Carpets, Galleons) ---
    "Sky Island",
    "Lava River",
    "Magic Carpet Race",
    "Dragon Flightpath",
    "Pirate Bay",
    "Cobblestone Avenue",
    "Crystal Gorge",
    "Fairy Forest",
    "Steampunk Skyway",
    "Dwarven Bridge",

    # --- Category 10: Logistics & Industrial (Trains, Transports) ---
    "Freight Rail",
    "Cargo River Route",
    "Cargo Conveyor",
    "Industrial Port",
    "Mining Track",
    "Wind Farm Road",
    "Solar Panel Grid",
    "Powerline Trail",
    "Refinery Strip",
    "Pipeline Route",
]

THEMES_LS_E_EXO_STA= [
    # --- Category 1: Urban & Metropolitan (city grid, roads, rooftops) ---
    "Downtown Skyline",
    "Harbor Waterfront",
    "Old Town Square",
    "Financial District",
    "Riverfront Cityscape",
    "Industrial Waterfront",
    "Chinatown District",
    "University Campus",
    "Airport Complex",
    "Train Station District",

    # --- Category 2: Coastal & Maritime (water, docks, shoreline) ---
    "Fishing Village Coast",
    "Naval Base Harbor",
    "Container Port",
    "Cruise Terminal Bay",
    "Lighthouse Peninsula",
    "Marina Resort",
    "Shipyard Complex",
    "Coral Reef Coastline",
    "Fjord Fishing Town",
    "Tidal Estuary",

    # --- Category 3: Industrial & Infrastructure (pipes, rails, machinery) ---
    "Oil Refinery Complex",
    "Power Plant District",
    "Railway Junction Hub",
    "Dam and Reservoir",
    "Mining Operations Site",
    "Wind Farm Plateau",
    "Solar Array Desert",
    "Freeway Interchange",
    "Sewage Treatment Plant",
    "Steel Mill Complex",

    # --- Category 4: Nature & Parks (forest, grassland, lakes) ---
    "National Park Valley",
    "Lakeside Campground",
    "Mountain Resort Village",
    "Vineyard Estate",
    "Safari Reserve",
    "Botanical Garden Complex",
    "Canyon River Bend",
    "Wetland Nature Reserve",
    "Alpine Meadow Village",
    "Coastal Nature Trail",

    # --- Category 5: Desert & Arid (sand, rock, canyons) ---
    "Desert Oasis Town",
    "Red Rock Canyon",
    "Adobe Pueblo Settlement",
    "Saharan Fortress Compound",
    "Mesa Archaeological Site",
    "Salt Flat Research Station",
    "Cactus Valley Outpost",
    "Desert Observatory Complex",
    "Sandstone Monastery",
    "Badlands Fossil Site",

    # --- Category 6: Historic & Cultural (stone paths, plazas, walls) ---
    "Medieval Castle Grounds",
    "Roman Forum District",
    "Egyptian Temple Complex",
    "Japanese Temple Garden",
    "Greek Acropolis Hill",
    "Gothic Cathedral Quarter",
    "Mayan Pyramid Grounds",
    "Colonial Plantation Estate",
    "Silk Road Caravan Town",
    "Viking Settlement",

    # --- Category 7: Military & Government (runways, parade grounds, fences) ---
    "Military Airbase",
    "Naval Dockyard",
    "Government Capitol Complex",
    "Embassy Compound",
    "Pentagon-style Headquarters",
    "Missile Defense Installation",
    "Army Training Camp",
    "Coast Guard Station",
    "Border Checkpoint Complex",
    "Submarine Base",

    # --- Category 8: Tropical & Equatorial (jungle, mangrove, coral) ---
    "Jungle Temple Ruins",
    "Volcanic Island Village",
    "Rainforest Research Station",
    "Tropical Plantation",
    "Mangrove Fishing Village",
    "Coral Island Resort",
    "Tea Plantation Hillside",
    "Waterfall Gorge Settlement",
    "Palm Beach Town",
    "Bamboo Forest Monastery",

    # --- Category 9: Winter & Alpine (snow, ice, frozen terrain) ---
    "Alpine Ski Resort",
    "Glacier Research Station",
    "Frozen Lake Village",
    "Tundra Outpost",
    "Ice Hotel Complex",
    "Nordic Fjord Village",
    "Polar Research Base",
    "Avalanche Control Station",
    "Snow-Covered Mountain Town",
    "Arctic Mining Camp",

    # --- Category 10: Sci-Fi & Fantasy (neon, lava, crystal, metal) ---
    "Mars Colony Settlement",
    "Cyberpunk Megacity Block",
    "Space Station Ring",
    "Floating Sky City",
    "Elven Forest Citadel",
    "Dwarven Mountain Fortress",
    "Steampunk Industrial City",
    "Underwater Dome Colony",
    "Crystal Cave Kingdom",
    "Post-Apocalyptic Outpost",
]

THEMES_BT_E_EXO_DYN= [
    # --- Category 1: Urban Roads ---
    "Urban residential street",
    "Downtown main avenue",
    "Business district plaza",
    "Riverfront promenade",
    "Highway cloverleaf ramp",
    "City center intersection",
    "Narrow stone alleyway",
    "Pedestrian shopping street",
    "Suburban cul-de-sac",
    "Old town square",

    # --- Category 2: Highways & Nature Roads ---
    "Desert straight highway",
    "Mountain serpentine road",
    "Coastal cliffside road",
    "Forest logging track",
    "Canyon gravel path",
    "Highway rest area",
    "Farm-to-market road",
    "Industrial port road",
    "Snowy rural bypass",
    "Quiet country road",

    # --- Category 3: Parks & Leisure ---
    "Park jogging loop",
    "Botanical garden path",
    "Lakeside boardwalk",
    "Golf course cart path",
    "Zoo visitor trail",
    "Amusement park street",
    "Riverside bike lane",
    "Mountain resort plaza",
    "University open quad",
    "Sculpture park lawn",

    # --- Category 4: Industrial & Logistics ---
    "Open-pit mine road",
    "Oil refinery path",
    "Container yard lane",
    "Airport taxiway",
    "Lumber yard aisle",
    "Automotive test track",
    "Shipyard perimeter road",
    "Construction dirt path",
    "Solar farm gravel road",
    "Railroad maintenance way",

    # --- Category 5: Wild Terrain ---
    "Alpine hiking ridge",
    "Savanna safari track",
    "Jungle trekking trail",
    "Desert sand dune",
    "Muddy forest path",
    "Beach shoreline",
    "Volcanic ash slope",
    "Arctic tundra trail",
    "Marshland walkway",
    "Creek-side canyon path",

    # --- Category 6: Sports Tracks ---
    "Polo field turf",
    "Stadium running track",
    "Longboard downhill road",
    "Public park running track",
    "Velodrome banked track",
    "MTB downhill trail",
    "Outdoor ice rink",
    "Concrete skatepark",
    "Marathon finish stretch",
    "Triathlon cycling route",

    # --- Category 7: Waterways ---
    "Venice water canal",
    "Island lagoon path",
    "River rafting channel",
    "Marina boat fairway",
    "Flooded main street",
    "Arctic lead channel",
    "Swamp airboat trail",
    "Ocean regatta course",
    "Dam-top service road",
    "Surfing beach water-line",

    # --- Category 8: Disaster & Emergency ---
    "Fractured urban street",
    "Tornado debris road",
    "Scorched forest path",
    "Flood damaged pier",
    "Ghost town ruins",
    "Warzone rubble lane",
    "Landslide mountain pass",
    "Evacuation tent aisle",
    "Chemical leak zone",
    "Tsunami washed harbor",

    # --- Category 9: Rural & Agriculture ---
    "Cornfield irrigation path",
    "Country dirt road",
    "Quiet farm path",
    "Lavender field walk",
    "Pasture grazing lane",
    "Orchard harvest row",
    "Tea plantation trail",
    "Open meadow path",
    "Ranch perimeter road",
    "Highland herding path",

    # --- Category 10: Sci-Fi & Fantasy ---
    "Mars colony road",
    "Cyberpunk skyway",
    "Castle drawbridge",
    "Steampunk catwalk",
    "Wasteland highway",
    "Ancient temple path",
    "Elf tree-bridge",
    "Dwarf stone ramp",
    "Lunar rover track",
    "Alien planet trail",
]
